GPP=g++
CXXFLAGS=-O2 `wx-config --cppflags`
LDFLAGS=-s -lwx_gtk2_stc-2.8 `wx-config --libs` 
OBJS_DIR=../../temp/img_viewer/release.lnx

all: ../../bin/img_viewer.bin

include Makefile.common

clean:
	rm -rf ${OBJS} ../../bin/img_viewer.bin
	rm -f core

../../bin/img_viewer.bin: ${OBJS_DIR} ${OBJS}
	${GPP} ${OBJS} ${LDFLAGS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}
