GCC=i686-apple-darwin8-gcc
OPTS=-O3 -DZASKAR -Dpanic=printf -Dckfree=free -Dckalloc=malloc -Dckrealloc=realloc -DHAVE_CONFIG_H -Ihyper -Icommon -Imisc -Icpp/cpplib -I.
OBJS_DIR=../../../../temp/parser/release.m32
LDFLAGS=-s

all: ../bin/cbrowser.bin

include Makefile.common

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

../bin:
	mkdir ../bin

../bin/cbrowser.bin: ../bin ${OBJS_DIR} ${OBJS}
	${GCC} ${OBJS} ${LDFLAGS} -o $@


clean:
	rm -f ../bin/cbrowser.bin
	rm -f ${OBJS} 
