GCC=i686-apple-darwin8-gcc
OPTS=-O3 -DZASKAR -Dpanic=printf -Dckfree=free -Dckalloc=malloc -Dckrealloc=realloc -DHAVE_CONFIG_H -Ihyper -Icommon -Imisc -Icpp/cpplib -I.
OBJS_DIR=../../../../release.m32/parser
LDFLAGS=-s

all: ../bin/cbrowser

include Makefile.common

${OBJS_DIR}:
	mkdir ${OBJS_DIR}

../bin:
	mkdir ../bin

../bin/cbrowser: ../bin ${OBJS_DIR} ${OBJS}
	${GCC} ${OBJS} ${LDFLAGS} -o $@


clean:
	rm -f ../bin/cbrowser 
	rm -f ${OBJS} 