GCC=gcc
OPTS= -O3 -DZASKAR -Dpanic=printf -Dckfree=free -Dckalloc=malloc -Dckrealloc=realloc -DHAVE_CONFIG_H -Ihyper -Icommon -Imisc -Icpp/cpplib -I.  
OBJS_DIR=../temp/parser/release.lnx
LDFLAGS=-s

all: ${OBJS_DIR} ../bin/cbrowser.bin

include Makefile.common

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

../bin:
	mkdir ../bin
	
../bin/cbrowser.bin: ../bin ${OBJS}
	${GCC} ${OBJS} ${LDFLAGS} -o $@


clean:
	rm -f ../bin/cbrowser.bin
	rm -f ${OBJS}
